service: user-demo

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MONGODB_URI: ${file(./config.json):MONGODB_URI}
    JWT_SECRET: ${file(./config.json):JWT_SECRET}

package:
  individually: true

functions:
  register:
    handler: dist/handler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  login:
    handler: dist/handler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  secureRoute:
    handler: dist/handler.secureRoute
    events:
      - http:
          path: secureRoute
          method: get
          authorizer: authorizerFunc
          cors: true

  authorizerFunc:
    handler: dist/handler.authorizerFunc
    cors: true
